/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stm32f401xe.h>
#include "systick.h"
#include "myprintf.h"
#include "usart.h"
#include "gpio.h"
#include "ttys.h"

char key;
bool event = false;
volatile uint32_t j = 0;

int main(void)
{
	myprintf_init();
	gpio_init(GPIOA, PIN3, ALTFUNC);
	usart_init(USART2, GPIOA, PIN3, ALTFUNC7);
	uart2rx_int();
	ttys_init();
    while (1)
    {


    	ttys_run();



    }
}
